accent = "#509475"
cursor = "#D7C995"
foreground = "#C1C497"
background = "#111c18"
selection_foreground = "#111C18"
selection_background = "#C1C497"

base00 = "#111c18"
base01 = "#23372B"
base02 = "#53685B"
base03 = "#53685B"
base04 = "#F6F5DD"
base05 = "#C1C497"
base06 = "#111C18"
base07 = "#9eebb3"
base08 = "#FF5345"
base09 = "#E5C736"
base0A = "#459451"
base0B = "#549e6a"
base0C = "#2DD5B7"
base0D = "#509475"
base0E = "#D2689C"
base0F = "#db9f9c"

color0 = "#23372B"
color1 = "#FF5345"
color2 = "#549e6a"
color3 = "#459451"
color4 = "#509475"
color5 = "#D2689C"
color6 = "#2DD5B7"
color7 = "#F6F5DD"
color8 = "#53685B"
color9 = "#db9f9c"
color10 = "#63b07a"
color11 = "#E5C736"
color12 = "#ACD4CF"
color13 = "#75bbb3"
color14 = "#8CD3CB"
color15 = "#9eebb3"
