accent = "#509475"
cursor = "#D7C995"
foreground = "#C1C497"
background = "#111c18"
selection_foreground = "#111C18"
selection_background = "#C1C497"

base00 = "#111c18"
base01 = "#23372B"
base02 = "#32473B"
base03 = "#53685B"
base04 = "#81B8A8"
base05 = "#C1C497"
base06 = "#D6D5BC"
base07 = "#F7E8B2"

base08 = "#23372B"
base09 = "#FF5345"
base0A = "#549e6a"
base0B = "#459451"
base0C = "#509475"
base0D = "#D2689C"
base0E = "#2DD5B7"
base0F = "#F6F5DD"
base10 = "#53685B"
base11 = "#db9f9c"
base12 = "#63b07a"
base13 = "#E5C736"
base14 = "#ACD4CF"
base15 = "#75bbb3"
base16 = "#8CD3CB"
base17 = "#9eebb3"
