accent = "#509475"
cursor = "#D7C995"
foreground = "#C1C497"
background = "#111c18"
selection_foreground = "#111C18"
selection_background = "#C1C497"

base00 = "#111c18"
base01 = "#23372B"
base02 = "#32473B"
base03 = "#53685B"
base04 = "#81B8A8"
base05 = "#C1C497"
base06 = "#D6D5BC"
base07 = "#F7E8B2"

base08 = "#FF5345"
base09 = "#a2734b"
base0A = "#459451"
base0B = "#549e6a"
base0C = "#2DD5B7"
base0D = "#509475"
base0E = "#D2689C"
base0F = "#513925"
base10 = "#0c1512"
base11 = "#090f0d"
base12 = "#db9f9c"
base13 = "#E5C736"
base14 = "#63b07a"
base15 = "#8CD3CB"
base16 = "#ACD4CF"
base17 = "#75bbb3"
