accent = "#509475"
cursor = "#D7C995"
foreground = "#C1C497"
background = "#111c18"
selection_foreground = "#111C18"
selection_background = "#C1C497"

bg = "#111c18"
lighter_bg = "#23372B"
selection = "#32473B"
muted = "#53685B"
dark_fg = "#81B8A8"
fg = "#C1C497"
light_fg = "#D6D5BC"
bright_fg = "#F7E8B2"

red = "#FF5345"
yellow = "#459451"
orange = "#a2734b"
green = "#549e6a"
cyan = "#2DD5B7"
blue = "#509475"
purple = "#D2689C"
brown = "#513925"
dark_bg = "#0c1512"
darker_bg = "#090f0d"
bright_red = "#db9f9c"
bright_yellow = "#E5C736"
bright_green = "#63b07a"
bright_cyan = "#8CD3CB"
bright_blue = "#ACD4CF"
bright_purple = "#75bbb3"
