accent = "#7aa2f7"
cursor = "#c0caf5"
foreground = "#a9b1d6"
background = "#1a1b26"
selection_foreground = "#c0caf5"
selection_background = "#7aa2f7"

base00 = "#1a1b26"
base01 = "#24283b"
base02 = "#292e42"
base03 = "#414868"
base04 = "#565f89"
base05 = "#737aa2"
base06 = "#a9b1d6"
base07 = "#cfc9c2"

base08 = "#f7768e"
base09 = "#eb927b"
base0A = "#e0af68"
base0B = "#9ece6a"
base0C = "#449dab"
base0D = "#7aa2f7"
base0E = "#ad8ee6"
base0F = "#75493d"
base10 = "#13141c"
base11 = "#0e0e14"
base12 = "#ff7a93"
base13 = "#ff9e64"
base14 = "#b9f27c"
base15 = "#0db9d7"
base16 = "#7da6ff"
base17 = "#bb9af7"
