accent = "#7aa2f7"
cursor = "#c0caf5"
foreground = "#a9b1d6"
background = "#1a1b26"
selection_foreground = "#c0caf5"
selection_background = "#7aa2f7"

bg = "#1a1b26"
lighter_bg = "#24283b"
selection = "#292e42"
muted = "#414868"
dark_fg = "#565f89"
fg = "#737aa2"
light_fg = "#a9b1d6"
bright_fg = "#cfc9c2"

red = "#f7768e"
yellow = "#e0af68"
orange = "#eb927b"
green = "#9ece6a"
cyan = "#449dab"
blue = "#7aa2f7"
purple = "#ad8ee6"
brown = "#75493d"
dark_bg = "#13141c"
darker_bg = "#0e0e14"
bright_red = "#ff7a93"
bright_yellow = "#ff9e64"
bright_green = "#b9f27c"
bright_cyan = "#0db9d7"
bright_blue = "#7da6ff"
bright_purple = "#bb9af7"
