accent = "#7aa2f7"
cursor = "#c0caf5"
foreground = "#a9b1d6"
background = "#1a1b26"
selection_foreground = "#c0caf5"
selection_background = "#7aa2f7"

base00 = "#1A1B26"
base01 = "#16161E"
base02 = "#2F3549"
base03 = "#444B6A"
base04 = "#787C99"
base05 = "#A9B1D6"
base06 = "#CBCCD1"
base07 = "#D5D6DB"
base08 = "#C0CAF5"
base09 = "#A9B1D6"
base0A = "#0DB9D7"
base0B = "#9ECE6A"
base0C = "#B4F9F8"
base0D = "#2AC3DE"
base0E = "#BB9AF7"
base0F = "#F7768E"

color0 = "#32344a"
color1 = "#f7768e"
color2 = "#9ece6a"
color3 = "#e0af68"
color4 = "#7aa2f7"
color5 = "#ad8ee6"
color6 = "#449dab"
color7 = "#787c99"
color8 = "#444b6a"
color9 = "#ff7a93"
color10 = "#b9f27c"
color11 = "#ff9e64"
color12 = "#7da6ff"
color13 = "#bb9af7"
color14 = "#0db9d7"
color15 = "#acb0d0"
