[colors.primary]
background = "#212337"
foreground = "#37f499"

[colors.cursor]
text = "#212337"
cursor = "#37f499"

[colors.vi_mode_cursor]
text = "#212337"
cursor = "#37f499"

[colors.search.matches]
foreground = "#212337"
background = "#37f499"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#37f499"
background = "#37f499"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#212337"
red = "#37f499"
green = "#04d1f9"
yellow = "#f265b5"
blue = "#7081d0"
magenta = "#04d1f9"
cyan = "#7081d0"
white = "#f265b5"

[colors.bright]
black = "#37f499"
red = "#f16c75"
green = "#f1fc79"
yellow = "#ebfafa"
blue = "#a48cf2"
magenta = "#04d1f9"
cyan = "#f7c67f"
white = "#37f499"

[colors.dim]
black = "#37f499"
red = "#f16c75"
green = "#f1fc79"
yellow = "#ebfafa"
blue = "#a48cf2"
magenta = "#04d1f9"
cyan = "#f7c67f"
white = "#37f499"
