accent = "#7daea3"
cursor = "#bdae93"
foreground = "#d4be98"
background = "#282828"
selection_foreground = "#ebdbb2"
selection_background = "#d65d0e"

base00 = "#282828"
base01 = "#3c3836"
base02 = "#504945"
base03 = "#665c54"
base04 = "#7c6f64"
base05 = "#a89984"
base06 = "#bdae93"
base07 = "#d4be98"

base08 = "#ea6962"
base09 = "#e1875c"
base0A = "#d8a657"
base0B = "#a9b665"
base0C = "#89b482"
base0D = "#7daea3"
base0E = "#d3869b"
base0F = "#70432e"
base10 = "#1e1e1e"
base11 = "#161616"
base12 = "#ea6962"
base13 = "#d8a657"
base14 = "#a9b665"
base15 = "#89b482"
base16 = "#7daea3"
base17 = "#d3869b"
