accent = "#7daea3"
cursor = "#bdae93"
foreground = "#d4be98"
background = "#282828"
selection_foreground = "#ebdbb2"
selection_background = "#d65d0e"

base00 = "#292828"
base01 = "#32302f"
base02 = "#504945"
base03 = "#665c54"
base04 = "#bdae93"
base05 = "#ddc7a1"
base06 = "#ebdbb2"
base07 = "#fbf1c7"
base08 = "#ea6962"
base09 = "#e78a4e"
base0A = "#d8a657"
base0B = "#a9b665"
base0C = "#89b482"
base0D = "#7daea3"
base0E = "#d3869b"
base0F = "#bd6f3e"

color0 = "#3c3836"
color1 = "#ea6962"
color2 = "#a9b665"
color3 = "#d8a657"
color4 = "#7daea3"
color5 = "#d3869b"
color6 = "#89b482"
color7 = "#d4be98"
color8 = "#3c3836"
color9 = "#ea6962"
color10 = "#a9b665"
color11 = "#d8a657"
color12 = "#7daea3"
color13 = "#d3869b"
color14 = "#89b482"
color15 = "#d4be98"
