accent = "#7daea3"
cursor = "#bdae93"
foreground = "#d4be98"
background = "#282828"
selection_foreground = "#ebdbb2"
selection_background = "#d65d0e"

bg = "#282828"
lighter_bg = "#3c3836"
selection = "#504945"
muted = "#665c54"
dark_fg = "#7c6f64"
fg = "#a89984"
light_fg = "#bdae93"
bright_fg = "#d4be98"

red = "#ea6962"
yellow = "#d8a657"
orange = "#e1875c"
green = "#a9b665"
cyan = "#89b482"
blue = "#7daea3"
purple = "#d3869b"
brown = "#70432e"
dark_bg = "#1e1e1e"
darker_bg = "#161616"
bright_red = "#ea6962"
bright_yellow = "#d8a657"
bright_green = "#a9b665"
bright_cyan = "#89b482"
bright_blue = "#7daea3"
bright_purple = "#d3869b"
