accent = "0x7daea3"
active_border_color = "#458588"
active_tab_background = "#d65d0e"
background = "0x282828"
color0 = "0x3c3836"
color1 = "0xea6962"
color10 = "0xa9b665"
color11 = "0xd8a657"
color12 = "0x7daea3"
color13 = "0xd3869b"
color14 = "0x89b482"
color15 = "0xd4be98"
color2 = "0xa9b665"
color3 = "0xd8a657"
color4 = "0x7daea3"
color5 = "0xd3869b"
color6 = "0x89b482"
color7 = "0xd4be98"
color8 = "0x3c3836"
color9 = "0xea6962"
cursor = "#bdae93"
foreground = "0xd4be98"
selection_background = "#d65d0e"
selection_foreground = "#ebdbb2"
