accent = "#7daea3"
cursor = "#bdae93"
foreground = "#d4be98"
background = "#282828"
selection_foreground = "#ebdbb2"
selection_background = "#d65d0e"

base00 = "#282828"
base01 = "#3c3836"
base02 = "#504945"
base03 = "#665c54"
base04 = "#7c6f64"
base05 = "#a89984"
base06 = "#bdae93"
base07 = "#d4be98"

base08 = "#3c3836"
base09 = "#ea6962"
base0A = "#a9b665"
base0B = "#d8a657"
base0C = "#7daea3"
base0D = "#d3869b"
base0E = "#89b482"
base0F = "#d4be98"
base10 = "#3c3836"
base11 = "#ea6962"
base12 = "#a9b665"
base13 = "#d8a657"
base14 = "#7daea3"
base15 = "#d3869b"
base16 = "#89b482"
base17 = "#d4be98"
