accent = "#89b4fa"
cursor = "#f5e0dc"
foreground = "#cdd6f4"
background = "#1e1e2e"
selection_foreground = "#1e1e2e"
selection_background = "#f5e0dc"

base00 = "#1e1e2e"
base01 = "#313244"
base02 = "#45475a"
base03 = "#585b70"
base04 = "#6c7086"
base05 = "#9399b2"
base06 = "#bac2de"
base07 = "#cdd6f4"

base08 = "#f38ba8"
base09 = "#f6b6ab"
base0A = "#f9e2af"
base0B = "#a6e3a1"
base0C = "#94e2d5"
base0D = "#89b4fa"
base0E = "#f5c2e7"
base0F = "#7b5b55"
base10 = "#161622"
base11 = "#101019"
base12 = "#f38ba8"
base13 = "#f9e2af"
base14 = "#a6e3a1"
base15 = "#94e2d5"
base16 = "#89b4fa"
base17 = "#f5c2e7"
