accent = "#89b4fa"
cursor = "#f5e0dc"
foreground = "#cdd6f4"
background = "#1e1e2e"
selection_foreground = "#1e1e2e"
selection_background = "#f5e0dc"

base00 = "#1e1e2e"
base01 = "#313244"
base02 = "#45475a"
base03 = "#585b70"
base04 = "#6c7086"
base05 = "#9399b2"
base06 = "#bac2de"
base07 = "#cdd6f4"

base08 = "#45475a"
base09 = "#f38ba8"
base0A = "#a6e3a1"
base0B = "#f9e2af"
base0C = "#89b4fa"
base0D = "#f5c2e7"
base0E = "#94e2d5"
base0F = "#bac2de"
base10 = "#585b70"
base11 = "#f38ba8"
base12 = "#a6e3a1"
base13 = "#f9e2af"
base14 = "#89b4fa"
base15 = "#f5c2e7"
base16 = "#94e2d5"
base17 = "#a6adc8"
