accent = "#205EA6"
cursor = "#100F0F"
foreground = "#100F0F"
background = "#FFFCF0"
selection_foreground = "#100F0F"
selection_background = "#CECDC3"

bg = "#FFFCF0"
lighter_bg = "#E6E4D9"
selection = "#CECDC3"
muted = "#B7B5AC"
dark_fg = "#878580"
fg = "#6F6E69"
light_fg = "#403E3C"
bright_fg = "#100F0F"

red = "#D14D41"
yellow = "#D0A215"
orange = "#d0772b"
green = "#879A39"
cyan = "#3AA99F"
blue = "#205EA6"
purple = "#CE5D97"
brown = "#683b15"
dark_bg = "#f2efe4"
darker_bg = "#e5e2d8"
bright_red = "#D14D41"
bright_yellow = "#D0A215"
bright_green = "#879A39"
bright_cyan = "#3AA99F"
bright_blue = "#4385BE"
bright_purple = "#CE5D97"
