accent = "#205EA6"
cursor = "#100F0F"
foreground = "#100F0F"
background = "#FFFCF0"
selection_foreground = "#100F0F"
selection_background = "#CECDC3"

base00 = "#FFFCF0"
base01 = "#E6E4D9"
base02 = "#CECDC3"
base03 = "#B7B5AC"
base04 = "#878580"
base05 = "#6F6E69"
base06 = "#403E3C"
base07 = "#100F0F"

base08 = "#100F0F"
base09 = "#D14D41"
base0A = "#879A39"
base0B = "#D0A215"
base0C = "#205EA6"
base0D = "#CE5D97"
base0E = "#3AA99F"
base0F = "#FFFCF0"
base10 = "#100F0F"
base11 = "#D14D41"
base12 = "#879A39"
base13 = "#D0A215"
base14 = "#4385BE"
base15 = "#CE5D97"
base16 = "#3AA99F"
base17 = "#FFFCF0"
