accent = "#205EA6"
cursor = "#100F0F"
foreground = "#100F0F"
background = "#FFFCF0"
selection_foreground = "#100F0F"
selection_background = "#CECDC3"

base00 = "#FFFCF0"
base01 = "#F2F0E5"
base02 = "#E6E4D9"
base03 = "#CECDC3"
base04 = "#9F9D96"
base05 = "#403E3C"
base06 = "#282726"
base07 = "#100F0F"
base08 = "#AF3029"
base09 = "#BC5215"
base0A = "#AD8301"
base0B = "#66800B"
base0C = "#24837B"
base0D = "#205EA6"
base0E = "#5E409D"
base0F = "#A02F6F"

color0 = "#100F0F"
color1 = "#D14D41"
color2 = "#879A39"
color3 = "#D0A215"
color4 = "#205EA6"
color5 = "#CE5D97"
color6 = "#3AA99F"
color7 = "#FFFCF0"
color8 = "#100F0F"
color9 = "#D14D41"
color10 = "#879A39"
color11 = "#D0A215"
color12 = "#4385BE"
color13 = "#CE5D97"
color14 = "#3AA99F"
color15 = "#FFFCF0"
