accent = "#205EA6"
cursor = "#100F0F"
foreground = "#100F0F"
background = "#FFFCF0"
selection_foreground = "#100F0F"
selection_background = "#CECDC3"

base00 = "#FFFCF0"
base01 = "#E6E4D9"
base02 = "#CECDC3"
base03 = "#B7B5AC"
base04 = "#878580"
base05 = "#6F6E69"
base06 = "#403E3C"
base07 = "#100F0F"

base08 = "#D14D41"
base09 = "#d0772b"
base0A = "#D0A215"
base0B = "#879A39"
base0C = "#3AA99F"
base0D = "#205EA6"
base0E = "#CE5D97"
base0F = "#683b15"
base10 = "#f2efe4"
base11 = "#e5e2d8"
base12 = "#D14D41"
base13 = "#D0A215"
base14 = "#879A39"
base15 = "#3AA99F"
base16 = "#4385BE"
base17 = "#CE5D97"
