accent = "#205EA6"
cursor = "#100F0F"
foreground = "#100F0F"
background = "#FFFCF0"
selection_foreground = "#100F0F"
selection_background = "#CECDC3"

color0 = "#100F0F"
color1 = "#D14D41"
color2 = "#879A39"
color3 = "#D0A215"
color4 = "#205EA6"
color5 = "#CE5D97"
color6 = "#3AA99F"
color7 = "#FFFCF0"
color8 = "#100F0F"
color9 = "#D14D41"
color10 = "#879A39"
color11 = "#D0A215"
color12 = "#4385BE"
color13 = "#CE5D97"
color14 = "#3AA99F"
color15 = "#FFFCF0"

spectrum0 = "#879A39"
spectrum1 = "#3AA99F"
spectrum2 = "#205EA6"
spectrum3 = "#4385BE"
spectrum4 = "#8B7EC8"
spectrum5 = "#CE5D97"
spectrum6 = "#DA702C"
spectrum7 = "#D14D41"
