accent = "#1e66f5"
cursor = "#dc8a78"
foreground = "#4c4f69"
background = "#eff1f5"
selection_foreground = "#eff1f5"
selection_background = "#dc8a78"

base00 = "#eff1f5"
base01 = "#ccd0da"
base02 = "#bcc0cc"
base03 = "#9ca0b0"
base04 = "#6c6f85"
base05 = "#4c4f69"
base06 = "#dc8a78"
base07 = "#7287fd"
base08 = "#d20f39"
base09 = "#fe640b"
base0A = "#df8e1d"
base0B = "#40a02b"
base0C = "#179299"
base0D = "#1e66f5"
base0E = "#8839ef"
base0F = "#dd7878"

color0 = "#bcc0cc"
color1 = "#d20f39"
color2 = "#40a02b"
color3 = "#df8e1d"
color4 = "#1e66f5"
color5 = "#ea76cb"
color6 = "#179299"
color7 = "#5c5f77"
color8 = "#acb0be"
color9 = "#d20f39"
color10 = "#40a02b"
color11 = "#df8e1d"
color12 = "#1e66f5"
color13 = "#ea76cb"
color14 = "#179299"
color15 = "#6c6f85"
