accent = "#1e66f5"
cursor = "#dc8a78"
foreground = "#4c4f69"
background = "#eff1f5"
selection_foreground = "#eff1f5"
selection_background = "#dc8a78"

base00 = "#eff1f5"
base01 = "#dce0e8"
base02 = "#ccd0da"
base03 = "#acb0be"
base04 = "#9ca0b0"
base05 = "#8c8fa1"
base06 = "#5c5f77"
base07 = "#4c4f69"

base08 = "#bcc0cc"
base09 = "#d20f39"
base0A = "#40a02b"
base0B = "#df8e1d"
base0C = "#1e66f5"
base0D = "#ea76cb"
base0E = "#179299"
base0F = "#5c5f77"
base10 = "#acb0be"
base11 = "#d20f39"
base12 = "#40a02b"
base13 = "#df8e1d"
base14 = "#1e66f5"
base15 = "#ea76cb"
base16 = "#179299"
base17 = "#6c6f85"
