accent = "#1e66f5"
cursor = "#dc8a78"
foreground = "#4c4f69"
background = "#eff1f5"
selection_foreground = "#eff1f5"
selection_background = "#dc8a78"

base00 = "#eff1f5"
base01 = "#dce0e8"
base02 = "#ccd0da"
base03 = "#acb0be"
base04 = "#9ca0b0"
base05 = "#8c8fa1"
base06 = "#5c5f77"
base07 = "#4c4f69"

base08 = "#d20f39"
base09 = "#d84e2b"
base0A = "#df8e1d"
base0B = "#40a02b"
base0C = "#179299"
base0D = "#1e66f5"
base0E = "#ea76cb"
base0F = "#6c2715"
base10 = "#e3e4e8"
base11 = "#d7d8dc"
base12 = "#d20f39"
base13 = "#df8e1d"
base14 = "#40a02b"
base15 = "#179299"
base16 = "#1e66f5"
base17 = "#ea76cb"
