accent = "#1e66f5"
cursor = "#dc8a78"
foreground = "#4c4f69"
background = "#eff1f5"
selection_foreground = "#eff1f5"
selection_background = "#dc8a78"

bg = "#eff1f5"
lighter_bg = "#dce0e8"
selection = "#ccd0da"
muted = "#acb0be"
dark_fg = "#9ca0b0"
fg = "#8c8fa1"
light_fg = "#5c5f77"
bright_fg = "#4c4f69"

red = "#d20f39"
yellow = "#df8e1d"
orange = "#d84e2b"
green = "#40a02b"
cyan = "#179299"
blue = "#1e66f5"
purple = "#ea76cb"
brown = "#6c2715"
dark_bg = "#e3e4e8"
darker_bg = "#d7d8dc"
bright_red = "#d20f39"
bright_yellow = "#df8e1d"
bright_green = "#40a02b"
bright_cyan = "#179299"
bright_blue = "#1e66f5"
bright_purple = "#ea76cb"
