accent = "#f38d70"
cursor = "#c3b7b8"
foreground = "#e6d9db"
background = "#2c2525"
selection_foreground = "#e6d9db"
selection_background = "#403e41"

color0 = "#72696a"
color1 = "#fd6883"
color2 = "#adda78"
color3 = "#f9cc6c"
color4 = "#f38d70"
color5 = "#a8a9eb"
color6 = "#85dacc"
color7 = "#e6d9db"
color8 = "#948a8b"
color9 = "#ff8297"
color10 = "#c8e292"
color11 = "#fcd675"
color12 = "#f8a788"
color13 = "#bebffd"
color14 = "#9bf1e1"
color15 = "#f1e5e7"

spectrum0 = "#2c2525"
spectrum1 = "#3d2f2a"
spectrum2 = "#403e41"
spectrum3 = "#5b4a45"
spectrum4 = "#72696a"
spectrum5 = "#948a8b"
spectrum6 = "#c3b7b8"
spectrum7 = "#e6d9db"
