accent = "#f38d70"
cursor = "#c3b7b8"
foreground = "#e6d9db"
background = "#2c2525"
selection_foreground = "#e6d9db"
selection_background = "#403e41"

base00 = "#2c2525"
base01 = "#3d2f2a"
base02 = "#403e41"
base03 = "#5b4a45"
base04 = "#72696a"
base05 = "#948a8b"
base06 = "#c3b7b8"
base07 = "#e6d9db"

base08 = "#72696a"
base09 = "#fd6883"
base0A = "#adda78"
base0B = "#f9cc6c"
base0C = "#f38d70"
base0D = "#a8a9eb"
base0E = "#85dacc"
base0F = "#e6d9db"
base10 = "#948a8b"
base11 = "#ff8297"
base12 = "#c8e292"
base13 = "#fcd675"
base14 = "#f8a788"
base15 = "#bebffd"
base16 = "#9bf1e1"
base17 = "#f1e5e7"
