accent = "#f38d70"
cursor = "#c3b7b8"
foreground = "#e6d9db"
background = "#2c2525"
selection_foreground = "#e6d9db"
selection_background = "#403e41"

bg = "#2c2525"
lighter_bg = "#3d2f2a"
selection = "#403e41"
muted = "#5b4a45"
dark_fg = "#72696a"
fg = "#948a8b"
light_fg = "#c3b7b8"
bright_fg = "#e6d9db"

red = "#fd6883"
yellow = "#f9cc6c"
orange = "#fb9a77"
green = "#adda78"
cyan = "#85dacc"
blue = "#f38d70"
purple = "#a8a9eb"
brown = "#7d4d3b"
dark_bg = "#211b1b"
darker_bg = "#181414"
bright_red = "#ff8297"
bright_yellow = "#fcd675"
bright_green = "#c8e292"
bright_cyan = "#9bf1e1"
bright_blue = "#f8a788"
bright_purple = "#bebffd"
