accent = "#f38d70"
cursor = "#c3b7b8"
foreground = "#e6d9db"
background = "#2c2525"
selection_foreground = "#e6d9db"
selection_background = "#403e41"

base00 = "#2c2525"
base01 = "#3d2f2a"
base02 = "#403e41"
base03 = "#5b4a45"
base04 = "#72696a"
base05 = "#948a8b"
base06 = "#c3b7b8"
base07 = "#e6d9db"

base08 = "#fd6883"
base09 = "#fb9a77"
base0A = "#f9cc6c"
base0B = "#adda78"
base0C = "#85dacc"
base0D = "#f38d70"
base0E = "#a8a9eb"
base0F = "#7d4d3b"
base10 = "#211b1b"
base11 = "#181414"
base12 = "#ff8297"
base13 = "#fcd675"
base14 = "#c8e292"
base15 = "#9bf1e1"
base16 = "#f8a788"
base17 = "#bebffd"
