accent = "#f38d70"
cursor = "#c3b7b8"
foreground = "#e6d9db"
background = "#2c2525"
selection_foreground = "#e6d9db"
selection_background = "#403e41"

base00 = "#2c2525"
base01 = "#72696a"
base02 = "#948a8b"
base03 = "#948a8b"
base04 = "#e6d9db"
base05 = "#e6d9db"
base06 = "#e6d9db"
base07 = "#f1e5e7"
base08 = "#fd6883"
base09 = "#fcd675"
base0A = "#f9cc6c"
base0B = "#adda78"
base0C = "#85dacc"
base0D = "#f38d70"
base0E = "#a8a9eb"
base0F = "#ff8297"

color0 = "#72696a"
color1 = "#fd6883"
color2 = "#adda78"
color3 = "#f9cc6c"
color4 = "#f38d70"
color5 = "#a8a9eb"
color6 = "#85dacc"
color7 = "#e6d9db"
color8 = "#948a8b"
color9 = "#ff8297"
color10 = "#c8e292"
color11 = "#fcd675"
color12 = "#f8a788"
color13 = "#bebffd"
color14 = "#9bf1e1"
color15 = "#f1e5e7"
