accent = "#78824b"
cursor = "#c7c7c7"
foreground = "#c2c2b0"
background = "#222222"
selection_foreground = "#c2c2b0"
selection_background = "#78824b"

bg = "#222222"
lighter_bg = "#2c2c2c"
selection = "#383838"
muted = "#444444"
dark_fg = "#555555"
fg = "#666666"
light_fg = "#8a8a7e"
bright_fg = "#c2c2b0"

red = "#685742"
yellow = "#b36d43"
orange = "#8d6242"
green = "#5f875f"
cyan = "#c9a554"
blue = "#78824b"
purple = "#bb7744"
brown = "#463121"
dark_bg = "#191919"
darker_bg = "#121212"
bright_red = "#685742"
bright_yellow = "#b36d43"
bright_green = "#5f875f"
bright_cyan = "#c9a554"
bright_blue = "#78824b"
bright_purple = "#bb7744"
