accent = "#78824b"
cursor = "#c7c7c7"
foreground = "#c2c2b0"
background = "#222222"
selection_foreground = "#c2c2b0"
selection_background = "#78824b"

base00 = "#222222"
base01 = "#2c2c2c"
base02 = "#383838"
base03 = "#444444"
base04 = "#555555"
base05 = "#666666"
base06 = "#8a8a7e"
base07 = "#c2c2b0"

base08 = "#685742"
base09 = "#8d6242"
base0A = "#b36d43"
base0B = "#5f875f"
base0C = "#c9a554"
base0D = "#78824b"
base0E = "#bb7744"
base0F = "#463121"
base10 = "#191919"
base11 = "#121212"
base12 = "#685742"
base13 = "#b36d43"
base14 = "#5f875f"
base15 = "#c9a554"
base16 = "#78824b"
base17 = "#bb7744"
