accent = "#78824b"
cursor = "#c7c7c7"
foreground = "#c2c2b0"
background = "#222222"
selection_foreground = "#c2c2b0"
selection_background = "#78824b"

base00 = "#222222"
base01 = "#000000"
base02 = "#666666"
base03 = "#666666"
base04 = "#d7c483"
base05 = "#c2c2b0"
base06 = "#c2c2b0"
base07 = "#d7c483"
base08 = "#685742"
base09 = "#b36d43"
base0A = "#b36d43"
base0B = "#5f875f"
base0C = "#c9a554"
base0D = "#78824b"
base0E = "#bb7744"
base0F = "#685742"

color0 = "#000000"
color1 = "#685742"
color2 = "#5f875f"
color3 = "#b36d43"
color4 = "#78824b"
color5 = "#bb7744"
color6 = "#c9a554"
color7 = "#d7c483"
color8 = "#666666"
color9 = "#685742"
color10 = "#5f875f"
color11 = "#b36d43"
color12 = "#78824b"
color13 = "#bb7744"
color14 = "#c9a554"
color15 = "#d7c483"
