accent = "#78824b"
cursor = "#c7c7c7"
foreground = "#c2c2b0"
background = "#222222"
selection_foreground = "#c2c2b0"
selection_background = "#78824b"

color0 = "#000000"
color1 = "#685742"
color2 = "#5f875f"
color3 = "#b36d43"
color4 = "#78824b"
color5 = "#bb7744"
color6 = "#c9a554"
color7 = "#d7c483"
color8 = "#666666"
color9 = "#685742"
color10 = "#5f875f"
color11 = "#b36d43"
color12 = "#78824b"
color13 = "#bb7744"
color14 = "#c9a554"
color15 = "#d7c483"

spectrum0 = "#222222"
spectrum1 = "#2c2c2c"
spectrum2 = "#383838"
spectrum3 = "#444444"
spectrum4 = "#555555"
spectrum5 = "#666666"
spectrum6 = "#8a8a7e"
spectrum7 = "#c2c2b0"
