accent = "#7e9cd8"
cursor = "#c8c093"
foreground = "#dcd7ba"
background = "#1f1f28"
selection_foreground = "#c8c093"
selection_background = "#2d4f67"

base00 = "#1f1f28"
base01 = "#223249"
base02 = "#363646"
base03 = "#54546D"
base04 = "#727169"
base05 = "#938aa9"
base06 = "#c8c093"
base07 = "#dcd7ba"

base08 = "#c34043"
base09 = "#c17158"
base0A = "#c0a36e"
base0B = "#76946a"
base0C = "#6a9589"
base0D = "#7e9cd8"
base0E = "#957fb8"
base0F = "#60382c"
base10 = "#17171e"
base11 = "#111116"
base12 = "#e82424"
base13 = "#e6c384"
base14 = "#98bb6c"
base15 = "#7aa89f"
base16 = "#7fb4ca"
base17 = "#938aa9"
