accent = "#7e9cd8"
cursor = "#c8c093"
foreground = "#dcd7ba"
background = "#1f1f28"
selection_foreground = "#c8c093"
selection_background = "#2d4f67"

base00 = "#1F1F28"
base01 = "#16161D"
base02 = "#223249"
base03 = "#54546D"
base04 = "#727169"
base05 = "#DCD7BA"
base06 = "#C8C093"
base07 = "#717C7C"
base08 = "#C34043"
base09 = "#FFA066"
base0A = "#C0A36E"
base0B = "#76946A"
base0C = "#6A9589"
base0D = "#7E9CD8"
base0E = "#957FB8"
base0F = "#D27E99"

color0 = "#090618"
color1 = "#c34043"
color2 = "#76946a"
color3 = "#c0a36e"
color4 = "#7e9cd8"
color5 = "#957fb8"
color6 = "#6a9589"
color7 = "#c8c093"
color8 = "#727169"
color9 = "#e82424"
color10 = "#98bb6c"
color11 = "#e6c384"
color12 = "#7fb4ca"
color13 = "#938aa9"
color14 = "#7aa89f"
color15 = "#dcd7ba"
