accent = "#56949f"
cursor = "#cecacd"
foreground = "#575279"
background = "#faf4ed"
selection_foreground = "#575279"
selection_background = "#dfdad9"

bg = "#faf4ed"
lighter_bg = "#f2e9e1"
selection = "#dfdad9"
muted = "#cecacd"
dark_fg = "#9893a5"
fg = "#908caa"
light_fg = "#6e6a86"
bright_fg = "#575279"

red = "#b4637a"
yellow = "#ea9d34"
orange = "#cf8057"
green = "#286983"
cyan = "#d7827e"
blue = "#56949f"
purple = "#907aa9"
brown = "#67402b"
dark_bg = "#ede7e1"
darker_bg = "#e1dbd5"
bright_red = "#b4637a"
bright_yellow = "#ea9d34"
bright_green = "#286983"
bright_cyan = "#d7827e"
bright_blue = "#56949f"
bright_purple = "#907aa9"
