accent = "#56949f"
cursor = "#cecacd"
foreground = "#575279"
background = "#faf4ed"
selection_foreground = "#575279"
selection_background = "#dfdad9"

base00 = "#faf4ed"
base01 = "#f2e9e1"
base02 = "#dfdad9"
base03 = "#cecacd"
base04 = "#9893a5"
base05 = "#908caa"
base06 = "#6e6a86"
base07 = "#575279"

base08 = "#b4637a"
base09 = "#cf8057"
base0A = "#ea9d34"
base0B = "#286983"
base0C = "#d7827e"
base0D = "#56949f"
base0E = "#907aa9"
base0F = "#67402b"
base10 = "#ede7e1"
base11 = "#e1dbd5"
base12 = "#b4637a"
base13 = "#ea9d34"
base14 = "#286983"
base15 = "#d7827e"
base16 = "#56949f"
base17 = "#907aa9"
