accent = "#56949f"
cursor = "#cecacd"
foreground = "#575279"
background = "#faf4ed"
selection_foreground = "#575279"
selection_background = "#dfdad9"

color0 = "#f2e9e1"
color1 = "#b4637a"
color2 = "#286983"
color3 = "#ea9d34"
color4 = "#56949f"
color5 = "#907aa9"
color6 = "#d7827e"
color7 = "#575279"
color8 = "#9893a5"
color9 = "#b4637a"
color10 = "#286983"
color11 = "#ea9d34"
color12 = "#56949f"
color13 = "#907aa9"
color14 = "#d7827e"
color15 = "#575279"

spectrum0 = "#faf4ed"
spectrum1 = "#f2e9e1"
spectrum2 = "#dfdad9"
spectrum3 = "#cecacd"
spectrum4 = "#9893a5"
spectrum5 = "#908caa"
spectrum6 = "#6e6a86"
spectrum7 = "#575279"
