accent = "#56949f"
cursor = "#cecacd"
foreground = "#575279"
background = "#faf4ed"
selection_foreground = "#575279"
selection_background = "#dfdad9"

base00 = "#faf4ed"
base01 = "#f2e9e1"
base02 = "#dfdad9"
base03 = "#cecacd"
base04 = "#9893a5"
base05 = "#908caa"
base06 = "#6e6a86"
base07 = "#575279"

base08 = "#f2e9e1"
base09 = "#b4637a"
base0A = "#286983"
base0B = "#ea9d34"
base0C = "#56949f"
base0D = "#907aa9"
base0E = "#d7827e"
base0F = "#575279"
base10 = "#9893a5"
base11 = "#b4637a"
base12 = "#286983"
base13 = "#ea9d34"
base14 = "#56949f"
base15 = "#907aa9"
base16 = "#d7827e"
base17 = "#575279"
