accent = "#56949f"
cursor = "#cecacd"
foreground = "#575279"
background = "#faf4ed"
selection_foreground = "#575279"
selection_background = "#dfdad9"

base00 = "#faf4ed"
base01 = "#fffaf3"
base02 = "#f2e9de"
base03 = "#9893a5"
base04 = "#797593"
base05 = "#575279"
base06 = "#575279"
base07 = "#cecacd"
base08 = "#b4637a"
base09 = "#ea9d34"
base0A = "#d7827e"
base0B = "#286983"
base0C = "#56949f"
base0D = "#907aa9"
base0E = "#ea9d34"
base0F = "#cecacd"

color0 = "#f2e9e1"
color1 = "#b4637a"
color2 = "#286983"
color3 = "#ea9d34"
color4 = "#56949f"
color5 = "#907aa9"
color6 = "#d7827e"
color7 = "#575279"
color8 = "#9893a5"
color9 = "#b4637a"
color10 = "#286983"
color11 = "#ea9d34"
color12 = "#56949f"
color13 = "#907aa9"
color14 = "#d7827e"
color15 = "#575279"
