accent = "#e68e0d"
cursor = "#eaeaea"
foreground = "#bebebe"
background = "#121212"
selection_foreground = "#bebebe"
selection_background = "#333333"

base00 = "#121212"
base01 = "#1e1e1e"
base02 = "#2a2a2a"
base03 = "#333333"
base04 = "#555555"
base05 = "#777777"
base06 = "#8a8a8d"
base07 = "#bebebe"

base08 = "#D35F5F"
base09 = "#c63d3d"
base0A = "#b91c1c"
base0B = "#FFC107"
base0C = "#bebebe"
base0D = "#e68e0d"
base0E = "#D35F5F"
base0F = "#631e1e"
base10 = "#0d0d0d"
base11 = "#090909"
base12 = "#B91C1C"
base13 = "#b90a0a"
base14 = "#FFC107"
base15 = "#eaeaea"
base16 = "#f59e0b"
base17 = "#B91C1C"
