accent = "#e68e0d"
cursor = "#eaeaea"
foreground = "#bebebe"
background = "#121212"
selection_foreground = "#bebebe"
selection_background = "#333333"

base00 = "#121212"
base01 = "#333333"
base02 = "#8a8a8d"
base03 = "#8a8a8d"
base04 = "#bebebe"
base05 = "#bebebe"
base06 = "#bebebe"
base07 = "#ffffff"
base08 = "#D35F5F"
base09 = "#b90a0a"
base0A = "#b91c1c"
base0B = "#FFC107"
base0C = "#bebebe"
base0D = "#e68e0d"
base0E = "#D35F5F"
base0F = "#B91C1C"

color0 = "#333333"
color1 = "#D35F5F"
color2 = "#FFC107"
color3 = "#b91c1c"
color4 = "#e68e0d"
color5 = "#D35F5F"
color6 = "#bebebe"
color7 = "#bebebe"
color8 = "#8a8a8d"
color9 = "#B91C1C"
color10 = "#FFC107"
color11 = "#b90a0a"
color12 = "#f59e0b"
color13 = "#B91C1C"
color14 = "#eaeaea"
color15 = "#ffffff"
