accent = "#e68e0d"
cursor = "#eaeaea"
foreground = "#bebebe"
background = "#121212"
selection_foreground = "#bebebe"
selection_background = "#333333"

bg = "#121212"
lighter_bg = "#1e1e1e"
selection = "#2a2a2a"
muted = "#333333"
dark_fg = "#555555"
fg = "#777777"
light_fg = "#8a8a8d"
bright_fg = "#bebebe"

red = "#D35F5F"
yellow = "#b91c1c"
orange = "#c63d3d"
green = "#FFC107"
cyan = "#bebebe"
blue = "#e68e0d"
purple = "#D35F5F"
brown = "#631e1e"
dark_bg = "#0d0d0d"
darker_bg = "#090909"
bright_red = "#B91C1C"
bright_yellow = "#b90a0a"
bright_green = "#FFC107"
bright_cyan = "#eaeaea"
bright_blue = "#f59e0b"
bright_purple = "#B91C1C"
