accent = "#81a1c1"
cursor = "#d8dee9"
foreground = "#d8dee9"
background = "#2e3440"
selection_foreground = "#d8dee9"
selection_background = "#4c566a"

base00 = "#2e3440"
base01 = "#3b4252"
base02 = "#434c5e"
base03 = "#4c566a"
base04 = "#667080"
base05 = "#8690a0"
base06 = "#adb5c4"
base07 = "#d8dee9"

base08 = "#3b4252"
base09 = "#bf616a"
base0A = "#a3be8c"
base0B = "#ebcb8b"
base0C = "#81a1c1"
base0D = "#b48ead"
base0E = "#88c0d0"
base0F = "#e5e9f0"
base10 = "#4c566a"
base11 = "#bf616a"
base12 = "#a3be8c"
base13 = "#ebcb8b"
base14 = "#81a1c1"
base15 = "#b48ead"
base16 = "#8fbcbb"
base17 = "#eceff4"
