accent = "#81a1c1"
cursor = "#d8dee9"
foreground = "#d8dee9"
background = "#2e3440"
selection_foreground = "#d8dee9"
selection_background = "#4c566a"

color0 = "#3b4252"
color1 = "#bf616a"
color2 = "#a3be8c"
color3 = "#ebcb8b"
color4 = "#81a1c1"
color5 = "#b48ead"
color6 = "#88c0d0"
color7 = "#e5e9f0"
color8 = "#4c566a"
color9 = "#bf616a"
color10 = "#a3be8c"
color11 = "#ebcb8b"
color12 = "#81a1c1"
color13 = "#b48ead"
color14 = "#8fbcbb"
color15 = "#eceff4"

spectrum0 = "#a3be8c"
spectrum1 = "#8fbcbb"
spectrum2 = "#88c0d0"
spectrum3 = "#81a1c1"
spectrum4 = "#5e81ac"
spectrum5 = "#b48ead"
spectrum6 = "#ebcb8b"
spectrum7 = "#bf616a"
