accent = "#81a1c1"
cursor = "#d8dee9"
foreground = "#d8dee9"
background = "#2e3440"
selection_foreground = "#d8dee9"
selection_background = "#4c566a"

base00 = "#2e3440"
base01 = "#3b4252"
base02 = "#434c5e"
base03 = "#4c566a"
base04 = "#667080"
base05 = "#8690a0"
base06 = "#adb5c4"
base07 = "#d8dee9"

base08 = "#bf616a"
base09 = "#d5967a"
base0A = "#ebcb8b"
base0B = "#a3be8c"
base0C = "#88c0d0"
base0D = "#81a1c1"
base0E = "#b48ead"
base0F = "#6a4b3d"
base10 = "#222730"
base11 = "#191c23"
base12 = "#bf616a"
base13 = "#ebcb8b"
base14 = "#a3be8c"
base15 = "#8fbcbb"
base16 = "#81a1c1"
base17 = "#b48ead"
