accent = "#81a1c1"
cursor = "#d8dee9"
foreground = "#d8dee9"
background = "#2e3440"
selection_foreground = "#d8dee9"
selection_background = "#4c566a"

bg = "#2e3440"
lighter_bg = "#3b4252"
selection = "#434c5e"
muted = "#4c566a"
dark_fg = "#667080"
fg = "#8690a0"
light_fg = "#adb5c4"
bright_fg = "#d8dee9"

red = "#bf616a"
yellow = "#ebcb8b"
orange = "#d5967a"
green = "#a3be8c"
cyan = "#88c0d0"
blue = "#81a1c1"
purple = "#b48ead"
brown = "#6a4b3d"
dark_bg = "#222730"
darker_bg = "#191c23"
bright_red = "#bf616a"
bright_yellow = "#ebcb8b"
bright_green = "#a3be8c"
bright_cyan = "#8fbcbb"
bright_blue = "#81a1c1"
bright_purple = "#b48ead"
