accent = "#82FB9C"
cursor = "#ddf7ff"
foreground = "#ddf7ff"
background = "#0B0C16"
selection_foreground = "#0B0C16"
selection_background = "#ddf7ff"

base00 = "#0B0C16"
base01 = "#151828"
base02 = "#1f253a"
base03 = "#2d3450"
base04 = "#6a6e95"
base05 = "#8e95b8"
base06 = "#b5c5db"
base07 = "#ddf7ff"

base08 = "#0B0C16"
base09 = "#50f872"
base0A = "#4fe88f"
base0B = "#50f7d4"
base0C = "#829dd4"
base0D = "#86a7df"
base0E = "#7cf8f7"
base0F = "#85E1FB"
base10 = "#6a6e95"
base11 = "#85ff9d"
base12 = "#9cf7c2"
base13 = "#a4ffec"
base14 = "#c4d2ed"
base15 = "#cddbf4"
base16 = "#d1fffe"
base17 = "#ddf7ff"
