accent = "#82FB9C"
cursor = "#ddf7ff"
foreground = "#ddf7ff"
background = "#0B0C16"
selection_foreground = "#0B0C16"
selection_background = "#ddf7ff"

bg = "#0B0C16"
lighter_bg = "#151828"
selection = "#1f253a"
muted = "#2d3450"
dark_fg = "#6a6e95"
fg = "#8e95b8"
light_fg = "#b5c5db"
bright_fg = "#ddf7ff"

red = "#50f872"
yellow = "#50f7d4"
orange = "#50f7a3"
green = "#4fe88f"
cyan = "#7cf8f7"
blue = "#829dd4"
purple = "#86a7df"
brown = "#287b51"
dark_bg = "#080910"
darker_bg = "#06060c"
bright_red = "#85ff9d"
bright_yellow = "#a4ffec"
bright_green = "#9cf7c2"
bright_cyan = "#d1fffe"
bright_blue = "#c4d2ed"
bright_purple = "#cddbf4"
