accent = "#82FB9C"
cursor = "#ddf7ff"
foreground = "#ddf7ff"
background = "#0B0C16"
selection_foreground = "#0B0C16"
selection_background = "#ddf7ff"

base00 = "#0B0C16"
base01 = "#0B0C16"
base02 = "#6a6e95"
base03 = "#6a6e95"
base04 = "#85E1FB"
base05 = "#ddf7ff"
base06 = "#0B0C16"
base07 = "#ddf7ff"
base08 = "#50f872"
base09 = "#a4ffec"
base0A = "#50f7d4"
base0B = "#4fe88f"
base0C = "#7cf8f7"
base0D = "#829dd4"
base0E = "#86a7df"
base0F = "#85ff9d"

color0 = "#0B0C16"
color1 = "#50f872"
color2 = "#4fe88f"
color3 = "#50f7d4"
color4 = "#829dd4"
color5 = "#86a7df"
color6 = "#7cf8f7"
color7 = "#85E1FB"
color8 = "#6a6e95"
color9 = "#85ff9d"
color10 = "#9cf7c2"
color11 = "#a4ffec"
color12 = "#c4d2ed"
color13 = "#cddbf4"
color14 = "#d1fffe"
color15 = "#ddf7ff"
