force_keyboard_focus = true                                                 # forces keyboard forcus to stay in Walker
close_when_open = true                                                      # close walker when invoking while already opened
selection_wrap = true                                                       # wrap list if at bottom or top
global_argument_delimiter = "#"                                             # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
keep_open_modifier = "shift"                                                # won't close on activation, but rather select the next item in the list
exact_search_prefix = "'"                                                   # disable fuzzy searching
theme = "omarchy-default"                                                   # theme to use
disable_mouse = false                                                       # disable mouse (on input and list only)
additional_theme_location = "~/.local/share/omarchy/default/walker/themes/"

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Start", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = "Escape"
next = "Down"
previous = "Up"
toggle_exact = "ctrl e"
resume_last_query = "ctrl r"
quick_activate = []

[providers]
default = [
  "desktopapplications",
  "menus",
  "websearch",
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"
