accent = "#7fbbb3"
cursor = "#d3c6aa"
foreground = "#d3c6aa"
background = "#2d353b"
selection_foreground = "#2d353b"
selection_background = "#d3c6aa"

color0 = "#475258"
color1 = "#e67e80"
color2 = "#a7c080"
color3 = "#dbbc7f"
color4 = "#7fbbb3"
color5 = "#d699b6"
color6 = "#83c092"
color7 = "#d3c6aa"
color8 = "#475258"
color9 = "#e67e80"
color10 = "#a7c080"
color11 = "#dbbc7f"
color12 = "#7fbbb3"
color13 = "#d699b6"
color14 = "#83c092"
color15 = "#d3c6aa"

spectrum0 = "#2d353b"
spectrum1 = "#343f44"
spectrum2 = "#3d484d"
spectrum3 = "#475258"
spectrum4 = "#4f585e"
spectrum5 = "#7a8478"
spectrum6 = "#9da9a0"
spectrum7 = "#d3c6aa"
