accent = "#7fbbb3"
cursor = "#d3c6aa"
foreground = "#d3c6aa"
background = "#2d353b"
selection_foreground = "#2d353b"
selection_background = "#d3c6aa"

base00 = "#2d353b"
base01 = "#343f44"
base02 = "#475258"
base03 = "#859289"
base04 = "#9da9a0"
base05 = "#d3c6aa"
base06 = "#e6e2cc"
base07 = "#fdf6e3"
base08 = "#e67e80"
base09 = "#e69875"
base0A = "#dbbc7f"
base0B = "#a7c080"
base0C = "#83c092"
base0D = "#7fbbb3"
base0E = "#d699b6"
base0F = "#9da9a0"

color0 = "#475258"
color1 = "#e67e80"
color2 = "#a7c080"
color3 = "#dbbc7f"
color4 = "#7fbbb3"
color5 = "#d699b6"
color6 = "#83c092"
color7 = "#d3c6aa"
color8 = "#475258"
color9 = "#e67e80"
color10 = "#a7c080"
color11 = "#dbbc7f"
color12 = "#7fbbb3"
color13 = "#d699b6"
color14 = "#83c092"
color15 = "#d3c6aa"
