accent = "#7fbbb3"
cursor = "#d3c6aa"
foreground = "#d3c6aa"
background = "#2d353b"
selection_foreground = "#2d353b"
selection_background = "#d3c6aa"

bg = "#2d353b"
lighter_bg = "#343f44"
selection = "#3d484d"
muted = "#475258"
dark_fg = "#4f585e"
fg = "#7a8478"
light_fg = "#9da9a0"
bright_fg = "#d3c6aa"

red = "#e67e80"
yellow = "#dbbc7f"
orange = "#e09d7f"
green = "#a7c080"
cyan = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
brown = "#704e3f"
dark_bg = "#21272c"
darker_bg = "#181d20"
bright_red = "#e67e80"
bright_yellow = "#dbbc7f"
bright_green = "#a7c080"
bright_cyan = "#83c092"
bright_blue = "#7fbbb3"
bright_purple = "#d699b6"
