accent = "#7fbbb3"
cursor = "#d3c6aa"
foreground = "#d3c6aa"
background = "#2d353b"
selection_foreground = "#2d353b"
selection_background = "#d3c6aa"

base00 = "#2d353b"
base01 = "#343f44"
base02 = "#3d484d"
base03 = "#475258"
base04 = "#4f585e"
base05 = "#7a8478"
base06 = "#9da9a0"
base07 = "#d3c6aa"

base08 = "#e67e80"
base09 = "#e09d7f"
base0A = "#dbbc7f"
base0B = "#a7c080"
base0C = "#83c092"
base0D = "#7fbbb3"
base0E = "#d699b6"
base0F = "#704e3f"
base10 = "#21272c"
base11 = "#181d20"
base12 = "#e67e80"
base13 = "#dbbc7f"
base14 = "#a7c080"
base15 = "#83c092"
base16 = "#7fbbb3"
base17 = "#d699b6"
