accent = "#8d8d8d"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#0d0d0d"
selection_foreground = "#0d0d0d"
selection_background = "#ffffff"

base00 = "#0d0d0d"
base01 = "#1a1a1a"
base02 = "#2e2e2e"
base03 = "#4a4a4a"
base04 = "#6b6b6b"
base05 = "#8d8d8d"
base06 = "#b6b6b6"
base07 = "#ffffff"

base08 = "#a4a4a4"
base09 = "#b9b9b9"
base0A = "#cecece"
base0B = "#b6b6b6"
base0C = "#b0b0b0"
base0D = "#8d8d8d"
base0E = "#9b9b9b"
base0F = "#5c5c5c"
base10 = "#090909"
base11 = "#070707"
base12 = "#a4a4a4"
base13 = "#cecece"
base14 = "#b6b6b6"
base15 = "#b0b0b0"
base16 = "#8d8d8d"
base17 = "#9b9b9b"
