accent = "#8d8d8d"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#0d0d0d"
selection_foreground = "#0d0d0d"
selection_background = "#ffffff"

bg = "#0d0d0d"
lighter_bg = "#1a1a1a"
selection = "#2e2e2e"
muted = "#4a4a4a"
dark_fg = "#6b6b6b"
fg = "#8d8d8d"
light_fg = "#b6b6b6"
bright_fg = "#ffffff"

red = "#a4a4a4"
yellow = "#cecece"
orange = "#b9b9b9"
green = "#b6b6b6"
cyan = "#b0b0b0"
blue = "#8d8d8d"
purple = "#9b9b9b"
brown = "#5c5c5c"
dark_bg = "#090909"
darker_bg = "#070707"
bright_red = "#a4a4a4"
bright_yellow = "#cecece"
bright_green = "#b6b6b6"
bright_cyan = "#b0b0b0"
bright_blue = "#8d8d8d"
bright_purple = "#9b9b9b"
