accent = "#7d82d9"
cursor = "#ffcead"
foreground = "#ffcead"
background = "#060B1E"
selection_foreground = "#060B1E"
selection_background = "#ffcead"

bg = "#060B1E"
lighter_bg = "#131a3a"
selection = "#252e56"
muted = "#3d4573"
dark_fg = "#6d7db6"
fg = "#9a96a8"
light_fg = "#c9b8a6"
bright_fg = "#ffcead"

red = "#ED5B5A"
yellow = "#E9BB4F"
orange = "#eb8b54"
green = "#92a593"
cyan = "#a3bfd1"
blue = "#7d82d9"
purple = "#c89dc1"
brown = "#75452a"
dark_bg = "#040816"
darker_bg = "#030610"
bright_red = "#faaaa9"
bright_yellow = "#f7dc9c"
bright_green = "#c4cfc4"
bright_cyan = "#dfeaf0"
bright_blue = "#c2c4f0"
bright_purple = "#ead7e7"
