accent = "#7d82d9"
cursor = "#ffcead"
foreground = "#ffcead"
background = "#060B1E"
selection_foreground = "#060B1E"
selection_background = "#ffcead"

base00 = "#060B1E"
base01 = "#131a3a"
base02 = "#252e56"
base03 = "#3d4573"
base04 = "#6d7db6"
base05 = "#9a96a8"
base06 = "#c9b8a6"
base07 = "#ffcead"

base08 = "#060B1E"
base09 = "#ED5B5A"
base0A = "#92a593"
base0B = "#E9BB4F"
base0C = "#7d82d9"
base0D = "#c89dc1"
base0E = "#a3bfd1"
base0F = "#F99957"
base10 = "#6d7db6"
base11 = "#faaaa9"
base12 = "#c4cfc4"
base13 = "#f7dc9c"
base14 = "#c2c4f0"
base15 = "#ead7e7"
base16 = "#dfeaf0"
base17 = "#ffcead"
