accent = "#7d82d9"
cursor = "#ffcead"
foreground = "#ffcead"
background = "#060B1E"
selection_foreground = "#060B1E"
selection_background = "#ffcead"

base00 = "#060B1E"
base01 = "#060B1E"
base02 = "#6d7db6"
base03 = "#6d7db6"
base04 = "#F99957"
base05 = "#ffcead"
base06 = "#060B1E"
base07 = "#ffcead"
base08 = "#ED5B5A"
base09 = "#f7dc9c"
base0A = "#E9BB4F"
base0B = "#92a593"
base0C = "#a3bfd1"
base0D = "#7d82d9"
base0E = "#c89dc1"
base0F = "#faaaa9"

color0 = "#060B1E"
color1 = "#ED5B5A"
color2 = "#92a593"
color3 = "#E9BB4F"
color4 = "#7d82d9"
color5 = "#c89dc1"
color6 = "#a3bfd1"
color7 = "#F99957"
color8 = "#6d7db6"
color9 = "#faaaa9"
color10 = "#c4cfc4"
color11 = "#f7dc9c"
color12 = "#c2c4f0"
color13 = "#ead7e7"
color14 = "#dfeaf0"
color15 = "#ffcead"
